version: "3.8"

services:
  mongo:
    image: mongo:6.0.11
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  mongodb:
  mongodb_config:
  postgres:
